# -*- coding: utf-8 -*-
"""Path7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PdgW-gay88msAfDfDnyY5MHKie372NPq
"""

# تثبيت المكتبات اللازمة لتشغيل الموقع وربطه بالإنترنت
!pip install streamlit -q
!pip install pyngrok -q

import streamlit as st

# إعدادات الصفحة الأساسية لتظهر بشكل هندسي أنيق
st.set_page_config(
    page_title="Path7 - مسارك الذكي",
    page_icon="🗺️",
    layout="centered"
)

# تخصيص واجهة المستخدم بالـ CSS (لضبط الخطوط والاتجاهات)
st.markdown("""
    <style>
    .reportview-container {
        direction: rtl;
        text-align: right;
    }
    h1, h2, h3, p {
        text-align: right;
        font-family: 'Tajawal', sans-serif;
    }
    .welcome-box {
        background-color: #f0f2f6;
        padding: 20px;
        border-radius: 10px;
        border-right: 5px solid #ff4b4b;
        margin-bottom: 25px;
    }
    </style>
""", unsafe_allow_html=True)

# ترويسة التطبيق
st.title("🗺️ مشروع Path7")
st.subheader("مساركِ الذكي لتخطيط الزيارات بجامعة IAU")
st.write("---")

# 1. التحديث الأول: اختيار الجنس وتخصيص الترحيب
gender = st.radio(
    "فضلاً، اختر جنسك لتخصيص تجربتك:",
    ["أنثى", "ذكر"],
    horizontal=True
)

# تحديد العبارات الترحيبية بناءً على اختيار الجنس
if gender == "أنثى":
    welcome_title = "أهلاً بكِ يا مهندسة المستقبل! ✨"
    welcome_msg = "سعادتنا كبيرة بزيارتكِ اليوم. دعينا نخطط لكِ جولة ملهمة تليق بتطلعاتكِ في رحاب جامعة الإمام عبد الرحمن بن فيصل."
else:
    welcome_title = "أهلاً بك يا مهندس المستقبل! ✨"
    welcome_msg = "سعداء جداً بزيارتك اليوم. دعنا نخطط لك جولة مميزة تليق بتطلعاتك في رحاب جامعة الإمام عبد الرحمن بن فيصل."

# عرض صندوق الترحيب التفاعلي
st.markdown(f"""
    <div class="welcome-box">
        <h3>{welcome_title}</h3>
        <p>{welcome_msg}</p>
    </div>
""", unsafe_allow_html=True)

# 2. التحديث الثاني: الطقس التفاعلي (شمس للصباح، وقمر ونجمة للمساء)
time_of_day = st.selectbox(
    "اختر وقت زيارتك المفضل:",
    ["صباحاً", "مساءً"]
)

st.write("### حالة الأجواء المتوقعة لزيارتك:")

# منطق الطقس التفاعلي
if time_of_day == "صباحاً":
    st.info("☀️ **الأجواء صباحية مشرقة ولطيفة!** ننصحكِ بارتداء نظارتكِ الشمسية والاستمتاع بالممرات المفتوحة في الجامعة.")
else:
    st.info("🌙✨ **الأجواء مسائية هادئة وجميلة!** إضاءة الجامعة تمنح المباني طابعاً هندسياً ساحراً في هذا الوقت.")


# 3. التحديث الثالث: النجوم التفاعلية (بدون تكرار الكلمات وبشكل مرتب)
st.write("---")
st.write("### تقييم وجهات مسار Path7:")
st.write("قيم وجهتك المفضلة في مسار اليوم:")

# شريط التقييم التفاعلي (من 1 إلى 5)
rating = st.slider("اسحب الشريط لتقييم الوجهة:", 1, 5, 5)

# تحويل التقييم الرقمي إلى نجوم حقيقية تظهر أفقياً وبشكل جذاب
stars_display = "⭐" * rating

# عرض النجوم بشكل بارز وجميل للمستخدم
st.markdown(f"""
    <div style="text-align: center; padding: 15px; background-color: #fff3cd; border-radius: 8px;">
        <span style="font-size: 24px;">التقييم الحالي:</span><br>
        <span style="font-size: 35px;">{stars_display}</span>
    </div>
""", unsafe_allow_html=True)

# بقية منطق مسارات Path7 (يمكنكِ إضافته هنا)...
st.write("---")
st.caption("تم التطوير بكل فخر | مشروع Path7 2026")

# 1. تشغيل الموقع في الخلفية
!streamlit run app.py &>/dev/null &

# 2. جلب رقم الـ IP (انسخيه بمجرد ظهوره)
print("--- 1. انسخي هذا الرقم (IP) ---")
!wget -q -O - ipv4.icanhazip.com

# 3. استخراج الرابط (انتظري ثواني)
print("\n--- 2. اضغطي على الرابط اللي بآخره .loca.lt ---")
!npx localtunnel --port 8501